exclude: "^node_modules|.git"
default_stages: [pre-commit]
fail_fast: false

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        files: "sheets_sync/.*"
        exclude: ".*json$|.*txt$|.*csv|.*md"
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-ast